apiVersion: apps/v1 #deployment is in the bucket of apps/v1 (recall pods were only in v1)
kind: Deployment #depl stand for deployment and tells us that this yaml is the config for posts deployment
metadata:
  name: posts-depl #we suffix with depl so we can distinguish that it is a deployment
spec:
  replicas: 1 #the number of pods we want to create running some particular image
  selector: #tells the deployment to look at all the different pods
    matchLabels: #tells deployment to match labels (key value pairs) of pods.
      app: posts #find all the pods that have this key value pair, we define the key value pair ourselves so it is arbitrary
  template: #where we specify the exact configuration of the pod we want the deployment to create, it is like a pod spec or pod config file
    metadata: #configuration for the pod that the deployment is going to make
      labels: #we want to set the following labels:
        app: posts #app:posts, this will allow the selector to matchLabels here. Labels are analogous to html class names. it allows us to grab a set of pods with label.
    spec:
      containers:
        - name: posts
          image: sandersonii/posts
---
apiVersion: v1 #Delimiter to create multiple objects inside a single file
kind: Service #service for communication
metadata:
  name: posts-clusterip-srv #our own arbitrary defined properties
spec:
  selector: #selects the pod to expose. We are telling the service to try to find ALL the pods with label app: posts
    app: posts #and expose those pods to the outside world. The label of the pod would have been set in the deployment config under spec:template:metadata:labels
  type: ClusterIP # service type OPTIONAL because this is default if we leave it out
  ports: #lists out all ports we want to expose on the target pods
    - name: posts
      protocol: TCP
      port: 4000 #port of the NodePort Service that internally redirects it to targetPort of the pod
      targetPort: 4000 #the port actually attached to the pod and its container and where traffic is ends up
#A deployment can sometimes have trouble determining which pods it should manage inside the cluster
#So if pods are created we need to tell the deployment that these are the ones its supposed to manage
#This is what the 'selector' and 'template:metadata' property are for
#To create the deployment you must run the command in the same dir the yaml is in:
#  kubectl apply -f {YAML_FILE}
#  *MAKE SURE YOU RUN 'minikube start' PRIOR TO THIS OR YOU WELL GET ERROR: The connection to the server localhost:8080 was refused - did you specify the right host or port?**